# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import rent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to=rent.models.upload_location)),
            ],
        ),
    ]
