# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import rent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('apartment', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('picture', models.ImageField(upload_to=rent.models.upload_location)),
            ],
        ),
    ]
